# Generated by Django 5.1.2 on 2024-10-25 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_department', '0002_initial'),
        ('app_school', '0001_initial'),
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Progress',
            fields=[
                ('roll_no', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('chemistry_mark', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('physics_mark', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('maths_mark', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('out_off', models.IntegerField(blank=True, default=300, editable=False, null=True)),
                ('gained_mark', models.FloatField(blank=True, editable=False, null=True)),
                ('percentage', models.FloatField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_teacher.teacher')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='app_department.department')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='app_school.school')),
            ],
        ),
    ]
