# Generated by Django 5.1.2 on 2024-10-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
