# Generated by Django 5.1.2 on 2024-10-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_progress',
            name='gained_mark',
            field=models.IntegerField(default=0),
        ),
    ]
