# Generated by Django 5.1.2 on 2024-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0003_alter_student_progress_gained_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_progress',
            name='total_mark',
        ),
        migrations.AddField(
            model_name='student_progress',
            name='out_off',
            field=models.IntegerField(blank=True, default=300, editable=False, null=True),
        ),
    ]
