# Generated by Django 5.1.2 on 2024-10-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0004_alter_student_progress_class_teacher_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student_progress',
        #     name='class_teacher',
        # ),
    ]
