# Generated by Django 5.1.2 on 2024-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0004_alter_student_progress_class_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_progress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
