# Generated by Django 5.1.2 on 2024-10-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0007_alter_teacher_performance_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='performance_rate',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
