# Generated by Django 5.1.2 on 2024-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0007_alter_student_progress_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_progress',
            name='roll_no',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
