# Generated by Django 5.1.2 on 2024-10-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0005_remove_student_progress_class_teacher_and_more'),
        ('app_progress_student', '0008_alter_teacher_performance_rate'),
    ]

    operations = [
    ]
