# Generated by Django 5.1.2 on 2024-10-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0010_student_progress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
