# Generated by Django 5.1.2 on 2024-10-24 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0001_initial'),
        ('app_progress_student', '0011_alter_student_progress_created_at_and_more'),
        ('app_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_progress',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='app_department.department'),
        ),
        migrations.AddField(
            model_name='student_progress',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='app_school.school'),
        ),
    ]
