# Generated by Django 5.1.2 on 2024-10-24 05:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0012_student_progress_department_id_and_more'),
        ('app_school', '0012_alter_school_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='app_school.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 5, 45, 18, 869374, tzinfo=datetime.timezone.utc)),
        ),
    ]
