# Generated by Django 5.1.2 on 2024-10-24 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_progress_student', '0013_teacher_school_id_alter_teacher_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 5, 50, 34, 231292, tzinfo=datetime.timezone.utc)),
        ),
    ]
