# Generated by Django 5.1.2 on 2024-10-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0001_initial'),
        ('app_progress_student', '0012_student_progress_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='app_progress_student.teacher'),
        ),
    ]
