# Generated by Django 5.1.2 on 2024-10-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0002_initial'),
        ('app_school', '0002_rename_principle_name_school_principal_name'),
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='app_teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_department', to='app_school.school'),
        ),
    ]
