# Generated by Django 5.1.2 on 2024-10-24 05:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0002_alter_department_hod_name'),
        ('app_school', '0012_alter_school_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod_name',
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 5, 45, 18, 872842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_department', to='app_school.school'),
        ),
    ]
