# Generated by Django 5.1.2 on 2024-10-24 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0004_department_hod_name_alter_department_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 5, 58, 19, 479358, tzinfo=datetime.timezone.utc)),
        ),
    ]
