# Generated by Django 5.1.2 on 2024-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0010_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
