# Generated by Django 5.1.2 on 2024-11-04 04:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0012_remove_department_school_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('active_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
