# Generated by Django 5.1.2 on 2024-10-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principle_name',
            new_name='principal_name',
        ),
    ]
