# Generated by Django 5.1.2 on 2024-10-30 07:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0012_remove_department_school_id'),
        ('app_school', '0006_alter_school_school_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='school',
            managers=[
                ('active_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='department_id',
            field=models.ManyToManyField(related_name='department_school', to='app_department.department'),
        ),
    ]
