# Generated by Django 5.1.2 on 2024-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
