# Generated by Django 5.1.2 on 2024-10-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school_id',
        ),
    ]
