# Generated by Django 5.1.2 on 2024-10-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0003_alter_department_hod_name_alter_department_school_id'),
        ('app_teacher', '0002_alter_teacher_department_id_alter_teacher_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers_app_teacher', to='app_department.department'),
        ),
    ]
