# Generated by Django 5.1.2 on 2024-10-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_school', '0002_rename_principle_name_school_principal_name'),
        ('app_teacher', '0003_alter_teacher_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers_app_teacher', to='app_school.school'),
        ),
    ]
