# Generated by Django 5.1.2 on 2024-10-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0005_alter_teacher_department_id_alter_teacher_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='employee_id',
            new_name='teacher_id',
        ),
    ]
