# Generated by Django 5.1.2 on 2024-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0009_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
