# Generated by Django 5.1.2 on 2024-11-02 02:44

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_department', '0012_remove_department_school_id'),
        ('app_teacher', '0010_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_id',
            field=models.ManyToManyField(blank=True, related_name='teachers_app_teacher', to='app_department.department'),
        ),
    ]
